/*

04.KH_JOIN및서브쿼리_실습문제.SQL

*/

-- 1. 70년대 생(1970~1979) 중 여자이면서 전씨인 사원의 이름과 주민번호, 부서 명, 직급 조회

--ORACLE

SELECT EMP_NAME "이름"
       ,EMP_NO "주민번호"
       ,DEPT_TITLE "부서 명"
       ,J.JOB_CODE "직급"
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.JOB_CODE = J.JOB_CODE(+)
AND SUBSTR(EMP_NO,1,2) LIKE '7_'
AND SUBSTR(EMP_NO,8,1) = '2'
AND EMP_NAME LIKE '전%';

-- ANSI
SELECT EMP_NAME "이름"
       ,EMP_NO "주민번호"
       ,DEPT_TITLE "부서 명"
       ,J.JOB_CODE "직급"
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
LEFT JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE SUBSTR(EMP_NO,1,2) LIKE '7_'
AND SUBSTR(EMP_NO,8,1) = '2'
AND EMP_NAME LIKE '전%';

-- 2. 나이 상 가장 막내의 사원 코드, 사원 명, 나이, 부서 명, 직급 명 조회 --> 가장 적은 나이를 어케고를까? (완료)

-- 가장 작은 나이 어떻게 뽑을지 생각하자.

-- ORACLE

SELECT EMP_ID "사원 코드"
       ,EMP_NAME "사원명"
       ,EXTRACT(YEAR FROM SYSDATE) -  (19||SUBSTR(EMP_NO,1,2)) "나이"
       --EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,2),'RR')) "나이"
       ,DEPT_TITLE "부서 명"
       ,JOB_NAME "직급 명"
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.JOB_CODE = J.JOB_CODE(+)
AND EMP_ID = '215';
--ORDER BY EXTRACT(YEAR FROM SYSDATE) -  (19||SUBSTR(EMP_NO,1,2)) ASC;
--GROUP BY EMP_ID;
--HAVING MIN(EXTRACT(YEAR FROM SYSDATE) -  (19||SUBSTR(EMP_NO,1,2)) );

-- ANSI
SELECT EMP_ID "사원 코드"
       ,EMP_NAME "사원명"
       ,EXTRACT(YEAR FROM SYSDATE) -  (19||SUBSTR(EMP_NO,1,2)) "나이"
       ,DEPT_TITLE "부서 명"
       ,JOB_NAME "직급 명"
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
LEFT JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE EMP_ID = '215';
--ORDER BY EXTRACT(YEAR FROM SYSDATE) -  (19||SUBSTR(EMP_NO,1,2)) ASC;

-- 3. 이름에 ‘형’이 들어가는 사원의 사원 코드, 사원 명, 직급 조회

-- ORACLE

SELECT EMP_ID "사원 코드"
       ,EMP_NAME "사원명"
       ,JOB_NAME "직급 명"
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND E.EMP_NAME LIKE '%형%';

-- ANSI
SELECT EMP_ID "사원 코드"
       ,EMP_NAME "사원명"
       ,JOB_NAME "직급 명"
FROM EMPLOYEE E
LEFT JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE E.EMP_NAME LIKE '%형%';

-- 4. 부서코드가 D5이거나 D6인 사원의 사원 명, 직급 명, 부서 코드, 부서 명 조회

-- ORACLE
SELECT EMP_NAME "사원 명"
       ,JOB_NAME "직급 명"
       ,DEPT_CODE "부서 코드"
       ,DEPT_TITLE "부서 명"
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE E.JOB_CODE = J.JOB_CODE
AND E.DEPT_CODE = D.DEPT_ID
AND DEPT_CODE IN ('D5', 'D6')
ORDER BY EMP_NAME ASC;

-- ANSI
SELECT EMP_NAME "사원 명"
       ,JOB_NAME "직급 명"
       ,DEPT_CODE "부서 코드"
       ,DEPT_TITLE "부서 명"
FROM EMPLOYEE E
LEFT JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
WHERE DEPT_CODE IN ('D5', 'D6')
ORDER BY EMP_NAME ASC;

-- 5. 보너스를 받는 사원의 사원 명, 부서 명, 지역 명 조회

-- ORACLE
SELECT EMP_NAME "사원 명"
       ,BONUS "보너스"
       ,DEPT_TITLE "부서 명"
       ,LOCAL_NAME "지역 명"
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE BONUS IS NOT NULL
AND E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE;

-- ANSI
SELECT EMP_NAME "사원 명"
       ,BONUS "보너스"
       ,DEPT_TITLE "부서 명"
       ,LOCAL_NAME "지역 명"
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
WHERE BONUS IS NOT NULL;

-- 6. 사원 명, 직급 명, 부서 명, 지역 명 조회

-- ORACLE
SELECT EMP_NAME "사원 명"
       ,JOB_NAME "직급 명"
       ,DEPT_TITLE "부서 명"
       ,LOCAL_NAME "지역 명"
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE E.JOB_CODE = J.JOB_CODE
AND E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE;

-- ANSI
SELECT EMP_NAME "사원 명"
       ,JOB_NAME "직급 명"
       ,DEPT_TITLE "부서 명"
       ,LOCAL_NAME "지역 명"
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE);

-- 7. 한국이나 일본에서 근무 중인 사원의 사원 명, 부서 명, 지역 명, 국가 명 조회

-- ORACLE
SELECT EMP_NAME "사원 명"
       ,DEPT_TITLE "부서 명"
       ,LOCAL_NAME "지역 명"
       ,NATIONAL_NAME "국가 명"
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE
AND L.NATIONAL_CODE = N.NATIONAL_CODE
AND N.NATIONAL_NAME IN ('한국','일본');

-- ANSI
SELECT EMP_NAME "사원 명"
       ,DEPT_TITLE "부서 명"
       ,LOCAL_NAME "지역 명"
       ,NATIONAL_NAME "국가 명"
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
JOIN NATIONAL N ON (L.NATIONAL_CODE = N.NATIONAL_CODE)
WHERE N.NATIONAL_NAME IN ('한국','일본');

-- 8. 한 사원과 같은 부서에서 일하는 사원의 이름 조회 (잠시 보류)

--ORACLE
SELECT E.EMP_NAME
       ,E.DEPT_CODE
       ,EE.EMP_NAME
FROM EMPLOYEE E, EMPLOYEE EE
WHERE E.DEPT_CODE = EE.DEPT_CODE
AND E.EMP_NAME != EE.EMP_NAME
ORDER BY E.EMP_NAME ASC, EE.EMP_NAME ASC;

--ANSI
SELECT E.EMP_NAME
       ,E.DEPT_CODE
       ,EE.EMP_NAME
FROM EMPLOYEE E
JOIN EMPLOYEE EE ON E.DEPT_CODE = EE.DEPT_CODE
WHERE E.EMP_NAME != EE.EMP_NAME
ORDER BY E.EMP_NAME ASC, EE.EMP_NAME ASC;

-- 9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원의 이름, 직급 명, 급여 조회(NVL 이용)

--ORACLE
SELECT EMP_NAME "사원 이름"
       ,JOB_NAME "직급 명"
       ,SALARY "급여"
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND E.JOB_CODE IN ('J4', 'J7');

--ANSI
SELECT EMP_NAME "사원 이름"
       ,JOB_NAME "직급 명"
       ,SALARY "급여"
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE E.JOB_CODE IN ('J4','J7');

-- 10. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서 명, 직급, 입사일, 순위 조회 (아직 못품)

--ORACLE
SELECT EMP_ID
       ,EMP_NAME
       ,DEPT_TITLE
       ,JOB_NAME
       ,HIRE_DATE
       -- ,((SALARY+(SALARY * NVL(BONUS,0)))*12)
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
ORDER BY ((SALARY+(SALARY * NVL(BONUS,0)))*12) DESC;

--ANSI
SELECT EMP_ID
       ,EMP_NAME
       ,DEPT_TITLE
       ,JOB_NAME
       ,HIRE_DATE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
ORDER BY ((SALARY+(SALARY * NVL(BONUS,0)))*12) DESC;